import React, { useState } from 'react';
import { DocumentAnalysis } from '../types';
import { Download, Copy, Check, X, ShieldCheck, Printer, Sparkles, FileText } from 'lucide-react';

interface ExportReportModalProps {
  analysis: DocumentAnalysis;
  isOpen: boolean;
  onClose: () => void;
}

export const ExportReportModal: React.FC<ExportReportModalProps> = ({ analysis, isOpen, onClose }) => {
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const generateMarkdownReport = () => {
    let md = `# SignSure AI Risk Analysis Report\n`;
    md += `**Analysis by SignSure AI**\n\n`;
    md += `**Document:** ${analysis.documentTitle} (${analysis.documentCategory})\n`;
    md += `**Risk Level:** ${analysis.overallRiskLevel} (Score: ${analysis.overallRiskScore}/100)\n`;
    md += `**Analysis Date:** ${analysis.uploadDate}\n\n`;

    md += `## Executive Summary\n${analysis.executiveSummary}\n\n`;

    md += `## Key Contract Details\n`;
    analysis.keyDetails.forEach((kd) => {
      md += `- **${kd.label}:** ${kd.value}\n`;
    });

    md += `\n## Clause Analysis & Risk Breakdown\n`;
    analysis.clauses.forEach((c, idx) => {
      md += `### ${idx + 1}. ${c.title} [${c.riskLevel.toUpperCase()} RISK]\n`;
      md += `**Category:** ${c.category}\n`;
      md += `**Simplified Explanation:** ${c.simplifiedExplanation}\n`;
      md += `**Risk Reason:** ${c.riskReasoning}\n`;
      md += `**Negotiation Recommendation:** ${c.recommendation}\n\n`;
    });

    md += `## Pre-Signing Audit Checklist\n`;
    analysis.preSigningChecklist.forEach((item) => {
      md += `- [ ] **[${item.severity.toUpperCase()}]** ${item.item}\n  *Action:* ${item.recommendation}\n`;
    });

    md += `\n---\n*Report generated by SignSure AI for informational risk assessment.*`;

    return md;
  };

  const handleCopyMarkdown = () => {
    navigator.clipboard.writeText(generateMarkdownReport());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const buildPrintableHtml = () => {
    const riskColor =
      analysis.overallRiskScore >= 75
        ? '#ef4444'
        : analysis.overallRiskScore >= 45
        ? '#f59e0b'
        : '#10b981';

    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Analysis by SignSure AI - ${analysis.documentTitle}</title>
  <style>
    @media print {
      body { margin: 0; padding: 20px; background: #fff !important; color: #0f172a !important; }
      .no-print { display: none !important; }
      .page-break { page-break-after: always; }
    }
    * { box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
      color: #1e293b;
      background: #f8fafc;
      margin: 0;
      padding: 40px 20px;
      line-height: 1.5;
    }
    .container {
      max-width: 850px;
      margin: 0 auto;
      background: #ffffff;
      padding: 40px;
      border-radius: 16px;
      box-shadow: 0 10px 25px rgba(0,0,0,0.08);
      border: 1px solid #e2e8f0;
    }
    .header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      border-bottom: 2px solid #e2e8f0;
      padding-bottom: 24px;
      margin-bottom: 28px;
    }
    .brand {
      display: flex;
      align-items: center;
      gap: 16px;
    }
    .brand-logo-wrap {
      width: 56px;
      height: 56px;
      background: #090d16;
      border-radius: 14px;
      padding: 6px;
      border: 1px solid rgba(255, 255, 255, 0.2);
      box-shadow: 0 4px 12px rgba(15, 23, 42, 0.3);
      display: flex;
      align-items: center;
      justify-content: center;
    }
    .brand-title {
      font-size: 24px;
      font-weight: 800;
      color: #0f172a;
      letter-spacing: -0.5px;
      margin: 0;
      line-height: 1.1;
    }
    .brand-title span {
      background: linear-gradient(135deg, #6366f1, #a855f7, #06b6d4);
      -webkit-background-clip: text;
      -webkit-text-fill-color: transparent;
    }
    .brand-sub {
      font-size: 11px;
      font-weight: 700;
      color: #0284c7;
      text-transform: uppercase;
      letter-spacing: 0.8px;
      margin-top: 2px;
    }
    .brand-slogan {
      font-size: 10px;
      font-weight: 600;
      color: #64748b;
      margin-top: 1px;
    }
    .score-badge {
      text-align: right;
      padding: 10px 18px;
      background: #f1f5f9;
      border-radius: 12px;
      border: 1px solid #cbd5e1;
    }
    .score-value {
      font-size: 24px;
      font-weight: 800;
      color: ${riskColor};
    }
    .score-label {
      font-size: 11px;
      font-weight: 700;
      text-transform: uppercase;
      color: #475569;
    }
    .doc-info {
      background: #f8fafc;
      border: 1px solid #e2e8f0;
      padding: 20px;
      border-radius: 12px;
      margin-bottom: 28px;
    }
    .doc-title {
      font-size: 20px;
      font-weight: 700;
      color: #0f172a;
      margin: 0 0 10px 0;
    }
    .meta-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
      gap: 12px;
      font-size: 12px;
      color: #475569;
    }
    .section-title {
      font-size: 14px;
      font-weight: 800;
      text-transform: uppercase;
      letter-spacing: 0.5px;
      color: #475569;
      margin-top: 28px;
      margin-bottom: 12px;
      padding-bottom: 6px;
      border-bottom: 1px solid #e2e8f0;
    }
    .summary-box {
      background: #eef2ff;
      border-left: 4px solid #6366f1;
      padding: 16px 20px;
      border-radius: 0 12px 12px 0;
      font-size: 14px;
      color: #1e1b4b;
      margin-bottom: 24px;
    }
    .details-grid {
      display: grid;
      grid-template-columns: repeat(2, 1fr);
      gap: 12px;
      margin-bottom: 24px;
    }
    .detail-card {
      background: #f8fafc;
      border: 1px solid #e2e8f0;
      padding: 12px 16px;
      border-radius: 8px;
    }
    .detail-label {
      font-size: 10px;
      font-weight: 700;
      color: #64748b;
      text-transform: uppercase;
    }
    .detail-val {
      font-size: 13px;
      font-weight: 600;
      color: #0f172a;
    }
    .clause-card {
      background: #ffffff;
      border: 1px solid #e2e8f0;
      border-radius: 12px;
      padding: 18px;
      margin-bottom: 16px;
    }
    .clause-card.high { border-left: 4px solid #ef4444; }
    .clause-card.medium { border-left: 4px solid #f59e0b; }
    .clause-card.low { border-left: 4px solid #10b981; }
    .clause-head {
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-bottom: 8px;
    }
    .clause-title {
      font-size: 14px;
      font-weight: 700;
      color: #0f172a;
    }
    .risk-tag {
      font-size: 10px;
      font-weight: 800;
      padding: 3px 8px;
      border-radius: 6px;
      text-transform: uppercase;
    }
    .tag-high { background: #fee2e2; color: #991b1b; }
    .tag-medium { background: #fef3c7; color: #92400e; }
    .tag-low { background: #d1fae5; color: #065f46; }
    .plain-text {
      background: #f1f5f9;
      padding: 10px 14px;
      border-radius: 8px;
      font-size: 13px;
      color: #334155;
      margin-bottom: 8px;
    }
    .fix-text {
      font-size: 12px;
      color: #047857;
      font-weight: 600;
      background: #ecfdf5;
      padding: 8px 12px;
      border-radius: 8px;
    }
    .checklist-item {
      display: flex;
      gap: 12px;
      padding: 10px 14px;
      border: 1px solid #e2e8f0;
      border-radius: 8px;
      margin-bottom: 8px;
      font-size: 12px;
    }
    .footer {
      margin-top: 40px;
      padding-top: 20px;
      border-top: 1px solid #e2e8f0;
      text-align: center;
      font-size: 11px;
      color: #94a3b8;
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <div class="brand">
        <div class="brand-logo-wrap">
          <svg viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg" style="width:100%; height:100%;">
            <defs>
              <linearGradient id="purpleCyanGradPrint" x1="0" y1="0" x2="100" y2="100" gradientUnits="userSpaceOnUse">
                <stop offset="0%" stop-color="#A855F7" />
                <stop offset="50%" stop-color="#6366F1" />
                <stop offset="100%" stop-color="#06B6D4" />
              </linearGradient>
              <linearGradient id="penGradPrint" x1="0" y1="0" x2="100" y2="100" gradientUnits="userSpaceOnUse">
                <stop offset="0%" stop-color="#38BDF8" />
                <stop offset="100%" stop-color="#1D4ED8" />
              </linearGradient>
            </defs>
            <path d="M75 18 C50 5, 20 20, 25 45 C30 70, 75 60, 75 80 C75 95, 45 100, 20 85" stroke="url(#purpleCyanGradPrint)" stroke-width="10" stroke-linecap="round" fill="none" />
            <rect x="30" y="24" width="38" height="50" rx="4" fill="#F8FAFC" />
            <path d="M49 32 H51 M50 30 V37 M43 37 H57 M43 37 L40 43 H46 Z M57 37 L54 43 H60 Z" stroke="#334155" stroke-width="1.5" stroke-linecap="round" />
            <line x1="38" y1="48" x2="60" y2="48" stroke="#64748B" stroke-width="2" stroke-linecap="round" />
            <line x1="38" y1="53" x2="52" y2="53" stroke="#818CF8" stroke-width="2" stroke-linecap="round" />
            <line x1="38" y1="58" x2="48" y2="58" stroke="#38BDF8" stroke-width="2" stroke-linecap="round" />
            <circle cx="41" cy="66" r="4" fill="#0EA5E9" />
            <path d="M39 66 L40.5 67.5 L43 64.5" stroke="white" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round" />
            <path d="M47 67 C48 65, 51 68, 53 66 C54 65, 56 67, 58 66" stroke="#1E293B" stroke-width="1.2" stroke-linecap="round" fill="none" />
            <path d="M72 32 L53 63 L49 68 L53 64 L72 32 Z" fill="url(#penGradPrint)" />
            <circle cx="73" cy="30" r="2.5" fill="#38BDF8" />
          </svg>
        </div>
        <div>
          <h1 class="brand-title">SignSure <span>AI</span></h1>
          <div class="brand-sub">Analysis by SignSure AI</div>
          <div class="brand-slogan">Understand Every Clause. Sign With Confidence.</div>
        </div>
      </div>
      <div class="score-badge">
        <div class="score-value">${analysis.overallRiskScore}/100</div>
        <div class="score-label">${analysis.overallRiskLevel}</div>
      </div>
    </div>

    <div class="doc-info">
      <h2 class="doc-title">${analysis.documentTitle}</h2>
      <div class="meta-grid">
        <div><strong>Category:</strong> ${analysis.documentCategory}</div>
        <div><strong>Analysis Date:</strong> ${analysis.uploadDate}</div>
        <div><strong>File Type:</strong> ${(analysis.fileType || 'pdf').toUpperCase()}</div>
      </div>
    </div>

    <div class="section-title">Executive Summary</div>
    <div class="summary-box">
      ${analysis.executiveSummary}
    </div>

    <div class="section-title">Key Details</div>
    <div class="details-grid">
      ${analysis.keyDetails
        .map(
          (kd) => `
        <div class="detail-card">
          <div class="detail-label">${kd.label}</div>
          <div class="detail-val">${kd.value}</div>
        </div>`
        )
        .join('')}
    </div>

    <div class="section-title">Clause-by-Clause Analysis</div>
    ${analysis.clauses
      .map(
        (c) => `
      <div class="clause-card ${c.riskLevel.toLowerCase()}">
        <div class="clause-head">
          <span class="clause-title">${c.title}</span>
          <span class="risk-tag tag-${c.riskLevel.toLowerCase()}">${c.riskLevel} Risk</span>
        </div>
        <div class="plain-text"><strong>Explanation:</strong> ${c.simplifiedExplanation}</div>
        <div style="font-size:11px; color:#64748b; margin-bottom:8px;"><strong>Risk Reason:</strong> ${c.riskReasoning}</div>
        <div class="fix-text"><strong>Fix / Negotiation:</strong> ${c.recommendation}</div>
      </div>`
      )
      .join('')}

    <div class="section-title">Pre-Signing Audit Checklist</div>
    ${analysis.preSigningChecklist
      .map(
        (chk) => `
      <div class="checklist-item">
        <strong>[${chk.severity.toUpperCase()}]</strong>
        <div>
          <div>${chk.item}</div>
          <div style="color:#059669; margin-top:2px;">Fix: ${chk.recommendation}</div>
        </div>
      </div>`
      )
      .join('')}

    <div class="footer">
      <strong>Official Risk Report — Analysis by SignSure AI</strong><br/>
      Generated on ${analysis.uploadDate} for ${analysis.documentTitle}. Confidential risk assessment.
    </div>
  </div>

  <script>
    window.onload = function() {
      setTimeout(function() { window.print(); }, 300);
    };
  </script>
</body>
</html>`;
  };

  const handlePrintPDF = () => {
    const htmlContent = buildPrintableHtml();

    // Try opening a print pop-up window
    const printWin = window.open('', '_blank');
    if (printWin) {
      printWin.document.open();
      printWin.document.write(htmlContent);
      printWin.document.close();
      return;
    }

    // Fallback if popup blocked: dynamic hidden iframe print
    let iframe = document.getElementById('signsure-print-frame') as HTMLIFrameElement;
    if (!iframe) {
      iframe = document.createElement('iframe');
      iframe.id = 'signsure-print-frame';
      iframe.style.position = 'fixed';
      iframe.style.right = '0';
      iframe.style.bottom = '0';
      iframe.style.width = '0px';
      iframe.style.height = '0px';
      iframe.style.border = 'none';
      document.body.appendChild(iframe);
    }

    const doc = iframe.contentWindow?.document || iframe.contentDocument;
    if (doc) {
      doc.open();
      doc.write(htmlContent);
      doc.close();

      setTimeout(() => {
        iframe.contentWindow?.focus();
        iframe.contentWindow?.print();
      }, 500);
    }
  };

  const handleDownloadHtmlReport = () => {
    const htmlContent = buildPrintableHtml();
    const blob = new Blob([htmlContent], { type: 'text/html;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Analysis_by_SignSure_AI_${analysis.documentTitle.replace(/[^a-zA-Z0-9]/g, '_')}.html`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-md">
      <div className="bg-slate-950/90 dark:bg-slate-950/90 light:bg-white backdrop-blur-2xl border border-white/10 light:border-slate-200 rounded-3xl w-full max-w-2xl overflow-hidden shadow-2xl flex flex-col max-h-[85vh] transition-colors">
        {/* Modal Header */}
        <div className="p-5 border-b border-white/10 light:border-slate-200 flex items-center justify-between bg-slate-900/60 dark:bg-slate-900/60 light:bg-slate-50 backdrop-blur-xl">
          <div className="flex items-center space-x-2.5">
            <ShieldCheck className="w-5 h-5 text-indigo-400" />
            <div>
              <h3 className="text-sm font-extrabold text-white dark:text-white light:text-slate-900 tracking-tight">SignSure AI PDF & Export Report</h3>
              <p className="text-[11px] text-indigo-300 dark:text-indigo-300 light:text-indigo-700 font-medium">Analysis by SignSure AI</p>
            </div>
          </div>
          <button onClick={onClose} className="p-2 text-slate-400 light:text-slate-600 hover:text-white dark:hover:text-white light:hover:text-slate-900 bg-slate-900/80 dark:bg-slate-900/80 light:bg-slate-100 border border-white/10 light:border-slate-200 rounded-xl transition">
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Report Content Preview */}
        <div className="p-6 overflow-y-auto space-y-6 text-slate-200 dark:text-slate-200 light:text-slate-800 text-xs font-mono bg-slate-950/70 dark:bg-slate-950/70 light:bg-slate-50 leading-relaxed">
          <div className="border-b border-white/10 light:border-slate-200 pb-4 flex items-center justify-between">
            <div>
              <div className="text-[10px] font-bold text-indigo-400 light:text-indigo-700 uppercase tracking-widest mb-0.5">Analysis by SignSure AI</div>
              <h1 className="text-base font-extrabold text-white dark:text-white light:text-slate-900">{analysis.documentTitle}</h1>
              <p className="text-indigo-300 dark:text-indigo-300 light:text-indigo-800 font-semibold mt-0.5">
                Category: {analysis.documentCategory} • Date: {analysis.uploadDate}
              </p>
            </div>
            <div className="px-3.5 py-1.5 rounded-xl bg-slate-900 dark:bg-slate-900 light:bg-white border border-white/10 light:border-slate-200 text-right">
              <span className="text-xs font-extrabold text-rose-400 light:text-rose-600 block">{analysis.overallRiskScore}/100</span>
              <span className="text-[10px] text-slate-300 dark:text-slate-300 light:text-slate-700 font-bold uppercase">{analysis.overallRiskLevel}</span>
            </div>
          </div>

          <div>
            <h4 className="font-bold text-slate-400 light:text-slate-600 uppercase tracking-wider mb-1 flex items-center space-x-1">
              <Sparkles className="w-3.5 h-3.5 text-indigo-400" />
              <span>Executive Summary</span>
            </h4>
            <p className="text-slate-300 dark:text-slate-300 light:text-slate-800 font-sans leading-relaxed bg-slate-900/80 dark:bg-slate-900/80 light:bg-white p-3.5 rounded-2xl border border-white/10 light:border-slate-200">{analysis.executiveSummary}</p>
          </div>

          <div>
            <h4 className="font-bold text-slate-400 light:text-slate-600 uppercase tracking-wider mb-2">High & Medium Risk Clauses</h4>
            <div className="space-y-3">
              {analysis.clauses
                .filter((c) => c.riskLevel === 'High' || c.riskLevel === 'Medium')
                .map((c) => (
                  <div key={c.id} className="p-3.5 bg-slate-900/80 dark:bg-slate-900/80 light:bg-white border border-white/10 light:border-slate-200 rounded-2xl">
                    <p className="font-bold text-rose-300 dark:text-rose-300 light:text-rose-700">
                      [{c.riskLevel}] {c.title}
                    </p>
                    <p className="text-slate-300 dark:text-slate-300 light:text-slate-700 mt-1 font-sans">{c.simplifiedExplanation}</p>
                    <p className="text-emerald-400 light:text-emerald-700 mt-1 font-mono text-[11px]">Fix: {c.recommendation}</p>
                  </div>
                ))}
            </div>
          </div>
        </div>

        {/* Modal Actions */}
        <div className="p-4 border-t border-white/10 light:border-slate-200 bg-slate-900/80 dark:bg-slate-900/80 light:bg-slate-100 backdrop-blur-xl flex flex-col sm:flex-row items-center justify-between gap-3">
          <span className="text-[10px] text-slate-400 light:text-slate-600 font-semibold hidden sm:inline">Analysis by SignSure AI</span>
          <div className="flex items-center gap-2 flex-wrap w-full sm:w-auto justify-stretch sm:justify-end">
            <button
              onClick={handlePrintPDF}
              className="flex-1 sm:flex-initial justify-center px-3.5 py-2.5 bg-gradient-to-r from-indigo-600 to-indigo-500 hover:from-indigo-500 hover:to-indigo-400 text-white text-xs rounded-xl font-bold transition flex items-center space-x-1.5 shadow-sm"
            >
              <Printer className="w-3.5 h-3.5" />
              <span>Print / PDF</span>
            </button>
            <button
              onClick={handleDownloadHtmlReport}
              className="flex-1 sm:flex-initial justify-center px-3.5 py-2.5 bg-slate-900 dark:bg-slate-900 light:bg-white hover:bg-slate-800 light:hover:bg-slate-200 text-slate-200 dark:text-slate-200 light:text-slate-800 text-xs rounded-xl border border-white/10 light:border-slate-300 font-semibold transition flex items-center space-x-1.5"
            >
              <Download className="w-3.5 h-3.5 text-slate-300 light:text-slate-700" />
              <span>HTML</span>
            </button>
            <button
              onClick={handleCopyMarkdown}
              className="flex-1 sm:flex-initial justify-center px-3.5 py-2.5 bg-slate-900 dark:bg-slate-900 light:bg-white hover:bg-slate-800 light:hover:bg-slate-200 text-slate-200 dark:text-slate-200 light:text-slate-800 text-xs rounded-xl border border-white/10 light:border-slate-300 font-semibold transition flex items-center space-x-1.5"
            >
              {copied ? (
                <>
                  <Check className="w-3.5 h-3.5 text-emerald-300" />
                  <span>Copied!</span>
                </>
              ) : (
                <>
                  <Copy className="w-3.5 h-3.5 text-white dark:text-white light:text-slate-700" />
                  <span>Markdown</span>
                </>
              )}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};


